### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by amrithathorath** [smuellerDD/acvpparser#1]
There are 2 errors when I try to run "make openssl".

```
amritha@thorath-vm:~/acvpparser-master$ make openssl
gcc -Wextra -Wall -pedantic -fPIE -O2 -Wno-long-long -std=gnu99 -Werror -DACVP_PARSER_IUT=\"openssl\" -Wno-gnu-zero-variadic-macro-arguments -D_FORTIFY_SOURCE=2 -fstack-protector-strong -fwrapv --param ssp-buffer-size=4 -Iparser   -c -o parser/binhexbin.o parser/binhexbin.c
...
...
gcc -Wextra -Wall -pedantic -fPIE -O2 -Wno-long-long -std=gnu99 -Werror -DACVP_PARSER_IUT=\"openssl\" -Wno-gnu-zero-variadic-macro-arguments -D_FORTIFY_SOURCE=2 -fstack-protector-strong -fwrapv --param ssp-buffer-size=4 -Iparser   -c -o parser/parser_common.o parser/parser_common.c
parser/parser_common.c: In function ‘parse_flagblock’:
parser/parser_common.c:433:9: error: ‘string’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
    if (!strncasecmp(string, conv->val.string,
         ^
parser/parser_common.c: At top level:
cc1: error: unrecognized command line option "-Wno-gnu-zero-variadic-macro-arguments" [-Werror]
```

Also, can you please confirm that the order of commands is correct:

- make openssl

- exec_openssl.sh

After this, response is generated and it is uploaded to server using acvp proxy?

**Comment by smuellerDD** [comment]
Am Freitag, 14. Dezember 2018, 22:00:04 CET schrieb amy123:

Hi amy123,

> There are 2 errors when I try to run "make openssl".
> 
> ```
> amritha@thorath-vm:~/acvpparser-master$ make openssl
> gcc -Wextra -Wall -pedantic -fPIE -O2 -Wno-long-long -std=gnu99 -Werror
> -DACVP_PARSER_IUT=\"openssl\" -Wno-gnu-zero-variadic-macro-arguments
> -D_FORTIFY_SOURCE=2 -fstack-protector-strong -fwrapv --param
> ssp-buffer-size=4 -Iparser   -c -o parser/binhexbin.o parser/binhexbin.c
> ...
> ...
> gcc -Wextra -Wall -pedantic -fPIE -O2 -Wno-long-long -std=gnu99 -Werror
> -DACVP_PARSER_IUT=\"openssl\" -Wno-gnu-zero-variadic-macro-arguments
> -D_FORTIFY_SOURCE=2 -fstack-protector-strong -fwrapv --param
> ssp-buffer-size=4 -Iparser   -c -o parser/parser_common.o
> parser/parser_common.c
 parser/parser_common.c: In function
> ‘parse_flagblock’:
> parser/parser_common.c:433:9: error: ‘string’ may be used uninitialized in
> this function [-Werror=maybe-uninitialized]
 if (!strncasecmp(string,
> conv->val.string,
>          ^
> parser/parser_common.c: At top level:
> cc1: error: unrecognized command line option
> "-Wno-gnu-zero-variadic-macro-arguments" [-Werror]
 ```

Interesting that this is marked as uninitialized. Initialize string to NULL at 
its definition. I will have that covered in the next round.
> 
> Also, can you please confirm that the order of commands is correct:
> 
> - make openssl
> 
> - exec_openssl.sh

The latter invokes the former, so no need to compile it manually.
> 
> After this, response is generated and it is uploaded to server using acvp
> proxy?

Sure. But I may believe that your standard Ubuntu OpenSSL may not have all 
FIPS bits. So, your milage may vary and you may need to adopt the backend to 
your implementation.

Welcome to the wonderful world of OpenSSL...
 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/smuellerDD/acvpparser/issues/1



Ciao
Stephan

**Comment by amrithathorath** [comment]
Oh I see. So let me ask this.
I've a test harness which can use the request files I have (got via acvp-proxy) and perform encrypt/decrypt operations and generate response files. In this case I do not need to run acvp-parser, but just upload results using acvp-proxy is that right?

**Comment by smuellerDD** [comment]
Am Montag, 17. Dezember 2018, 15:22:49 CET schrieb amy123:

Hi amy123,

> Oh I see. So let me ask this.
> I've a test harness which can use the request files I have (got via
> acvp-proxy) and perform encrypt/decrypt operations and generate response
> files. In this case I do not need to run acvp-parser, but just upload
> results using acvp-proxy is that right?

Yes, that is exactly the intention of the proxy. Or you use the parser on a 
Fedora 29 that has all OpenSSL bits needed. Or you modify the 
backend_openssl.c as needed.

Ciao
Stephan

**Comment by amrithathorath** [comment]
Great, thanks...
The crypto code I've generates the response in .txt format.
Can you please point me to a sample response json file (say for AES).

**Comment by smuellerDD** [comment]
Am Montag, 17. Dezember 2018, 20:56:25 CET schrieb amy123:

Hi amy123,

> Great, thanks...
> The crypto code I've generates the response in .txt format.
> Can you please point me to a sample response json file (say for AES).

see the --sample option.

Ciao
Stephan

**Comment by smuellerDD** [comment]
Am Dienstag, 18. Dezember 2018, 16:25:42 CET schrieb amy123:

Hi amy123,

> Please correct me if I'm doing it wrong. I'm running the following command
> to request sample vectors for AES.
> > ./acvp-proxy -m "OpenSSL (64 bit) (AESNI)" --sample --request -v -v
> 
> And each time it fails with this error:
> > int_thread_release, bad reference count
> > Aborted
> 
> I run ipcs and ipcrm and restart test and again same cycle continues....

The error is thrown by OpenSSL. Maybe you run into the following issue:

http://openssl.6102.n7.nabble.com/OpenSSL-1-0-1c-non-blocking-io-int-thread-release-bad-reference-count-td10483.html

With any OpenSSL code I use, I do not have that issue. So, I would think that 
some locking problem is at fault here in OpenSSL that is fixed in later 
relases.

For your case, I would suggest you need to disable threading support in 
config.h until you have updated your OpenSSL code base or you use curl that 
uses a different TLS provider.

Ciao
Stephan

**Comment by amrithathorath** [comment]
When I look into the config.h, there are 2 items I see related to threads: "ACVP_USE_PTHREAD" and "THREADING_MAX_THREADS". I can comment out the MAX_THREADS. But unfortunately I cannot touch "USE_PTHREAD". Later in the code, there's a check to see if "USE_PTHREAD" is defined or not...

```
#ifdef ACVP_TOTP_MQ_SERVER
# ifndef ACVP_USE_PTHREAD
#  error "TOTP Message Queue Server requires PTHREAD support"
# endif
#endif
```

Any suggestions to work around this?

Also can you please give me the versions of your OpenSSL and Curl you used so that I can try using the same ones.
Currently my OpenSSL versions are: 1.0.2j and fips-2.0.12
Curl version: 7.59.0

**Comment by smuellerDD** [comment]
Am Dienstag, 18. Dezember 2018, 16:54:35 CET schrieb amy123:

Hi amy123,

> When I look into the config.h, there are 2 items I see related to threads:
> "ACVP_USE_PTHREAD" and "THREADING_MAX_THREADS". I can comment out the
> MAX_THREADS. But unfortunately I cannot touch "USE_PTHREAD". Later in the
> code, there's a check to see if "USE_PTHREAD" is defined or not...
> 
> ```
> #ifdef ACVP_TOTP_MQ_SERVER
> # ifndef ACVP_USE_PTHREAD
> #  error "TOTP Message Queue Server requires PTHREAD support"
> # endif
> #endif
> ```
> 
> Any suggestions to work around this?

What does the comment in config.h say?

```
/*
 * Enable the TOTP message queue server
 * NOTE The message queue server requires ACVP_USE_PTHREAD to be set
 */
#define ACVP_TOTP_MQ_SERVER
```

So, if you undef threading you undef the MQ server support.

> 
> Also can you please give me the versions of your OpenSSL and Curl you used
> so that I can try using the same ones. Currently my OpenSSL versions are:
> 1.0.2j and fips-2.0.12
> Curl version: 7.59.0

I am using Fedora 29 with openssl 1.1.1. Curl should not be blamed.

Ciao
Stephan

**Comment by amrithathorath** [comment]
Thanks a lot for the suggestions Stephan.. I'll try them out...
