### ISSUE TITLE
How to use the api to compute the cmac value?

### ISSUE THREAD

**Issue by angelshadow** [smuellerDD/acvpparser#11]
HI, 
    Can you tell me how to use the libkcapi interface to calculate the mac value with aes-cmac .I only saw the use case of pbkdf with cmac in the test case. But I only want to use the interface to calculate the cmac value output, which interface should I invoke? 

Waiting for you response.
Thank you!

**Comment by smuellerDD** [comment]
Am Freitag, dem 19.03.2021 um 03:38 -0700 schrieb angelshadow:
> HI, 
>     Can you tell me how to use the libkcapi interface to calculate the mac
> value with aes-cmac .I only saw the use case of pbkdf with cmac in the test
> case. But I only want to use the interface to calculate the cmac value
> output, which interface should I invoke? 

see test/kcapi-main.c:cavs_hash()

Ciao
Stephan

**Comment by angelshadow** [comment]
It works. Thank you very much!
