### ISSUE TITLE
Can not build against OpenSSH

### ISSUE THREAD

**Issue by sumeetaci** [smuellerDD/acvpparser#12]
I can't build against openssh. I can't find backend code for openssh. There is an instruction to build.
backend_interfaces/openssh/README
There is no such file. Please suggest.

**Comment by smuellerDD** [comment]
Am Montag, dem 22.03.2021 um 13:14 -0700 schrieb sumeetaci:
> I can't build against openssh. I can't find backend code for openssh. There
> is an instruction to build.
> backend_interfaces/openssh/README
> There is no such file. Please suggest.
> 
> 
If you use a current OpenSSL and OpenSSH, you do not need to test OponSSH any
more as the KDF (the only cipher implemented by OpenSSH in the past) is now
moved to OpenSSL.

The current code for OpenSSL contains the SSH KDF test.

But if you use an old version of OpenSSH, you would need that backend.

**Comment by sumeetaci** [comment]
we are using 1.0.2k of OpenSSL, which doesn't have backend for openssh. Please suggest.

**Comment by smuellerDD** [comment]
Am Dienstag, dem 23.03.2021 um 13:26 -0700 schrieb sumeetaci:
> we are using 1.0.2k of OpenSSL, which doesn't have backend for openssh.
> Please suggest.

git pull
>

**Comment by sumeetaci** [comment]
Thank you for the support.

**Comment by Nagarjuna-jantali** [comment]
> Am Montag, dem 22.03.2021 um 13:14 -0700 schrieb sumeetaci:
> I can't build against openssh. I can't find backend code for openssh. There is an instruction to build. backend_interfaces/openssh/README There is no such file. Please suggest.
> If you use a current OpenSSL and OpenSSH, you do not need to test OponSSH any more as the KDF (the only cipher implemented by OpenSSH in the past) is now moved to OpenSSL. The current code for OpenSSL contains the SSH KDF test. But if you use an old version of OpenSSH, you would need that backend.

Hello,

Can you please tell which version of openssl contains openssh kdf test?

Thanks
Nagarjun

**Comment by smuellerDD** [comment]
Am Donnerstag, dem 15.04.2021 um 11:17 -0700 schrieb Nagarjun:
> > Am Montag, dem 22.03.2021 um 13:14 -0700 schrieb sumeetaci:
> > I can't build against openssh. I can't find backend code for openssh.
> > There is an instruction to build. backend_interfaces/openssh/README There
> > is no such file. Please suggest.
> > If you use a current OpenSSL and OpenSSH, you do not need to test OponSSH
> > any more as the KDF (the only cipher implemented by OpenSSH in the past)
> > is now moved to OpenSSL. The current code for OpenSSL contains the SSH KDF
> > test. But if you use an old version of OpenSSH, you would need that
> > backend.
> 
> Hello,
> 
> Can you please tell which version of openssl contains openssh kdf test?

Upstream does not have it yet.

But the OpenSSL versions in

Fedora 32/33, SLES 15 SP2 or the FIPS version from Canonical have it.

Ciao
Stephan
> 
> Thanks
> Nagarjun
>

**Comment by smuellerDD** [comment]
Issue resolved.
