### ISSUE TITLE
lrng tests failing with SHA256

### ISSUE THREAD

**Issue by sumeetaci** [smuellerDD/acvpparser#13]
We built the tool for lrng code. We are testing on Centos 7.  Input vector with algorithm SHA-1 is passing. But, input vector with algorithm SHA2-256 fails. Here are more details from verbose:
ACVPParser (22:37:38) Error: Cannot read data from kernel: -22
ACVPParser (22:37:38) Warning: Test execution failed with error -22
ACVPParser (22:37:38) Error: Test execution failed
ACVPParser (22:37:38) Debug: Freeing entry msg with data type 0
ACVPParser (22:37:38) Debug: Freeing entry len with data type 2
ACVPParser (22:37:38) Debug: Freeing entry md with data type 12
ACVPParser (22:37:38) Warning: Searched object: tests
ACVPParser (22:37:38) Error: Parsing processdata failed
ACVPParser (22:37:38) Warning: Searched object: testGroups

Any suggestions to solve this issue? Thanks.

**Comment by smuellerDD** [comment]
Am Donnerstag, dem 25.03.2021 um 10:40 -0700 schrieb sumeetaci:
> We built the tool for lrng code. Input vector with algorithm SHA-1 is passing.
> But, input vector with algorithm SHA2-256 fails. Here are more details from
> verbose:
> ACVPParser (22:37:38) Error: Cannot read data from kernel: -22
> ACVPParser (22:37:38) Warning: Test execution failed with error -22
> ACVPParser (22:37:38) Error: Test execution failed
> ACVPParser (22:37:38) Debug: Freeing entry msg with data type 0
> ACVPParser (22:37:38) Debug: Freeing entry len with data type 2
> ACVPParser (22:37:38) Debug: Freeing entry md with data type 12
> ACVPParser (22:37:38) Warning: Searched object: tests
> ACVPParser (22:37:38) Error: Parsing processdata failed
> ACVPParser (22:37:38) Warning: Searched object: testGroups
> 
> Any suggestions to solve this issue? Thanks.
> 

There is one and only one hash type supported for one given kernel when you
use the base conditioning and DRNG (i.e. you did not load a switchable
extension like lrng_drbg). When you say that SHA-1 is passing (and you truly
get results that pass the ACVP server validation, you have SHA-1 selected.
SHA2-256 is not available for the LRNG and thus not testable.

See also the output of /proc/lrng_type - it tells you which hash is in use.
Here is a snipped from my kernel:

$ cat /proc/lrng_type
DRNG name: ChaCha20 DRNG
Hash for reading entropy pool: SHA-256
Hash for operating aux entropy pool: SHA-256


See lrng_chacha20.c with the ifdef for CONFIG_CRYPTO_LIB_SHA256.


Side note: the provided switchable support that gives you access to
accelerated cipher implementations. So, if you use the switchable support by,
e.g., loading lrng_drbg, the algos should not be tested via the LRNG ACVTS
interface, but via a true test of the kernel crypto API which in this case is
the crypto provider (unlike when you use the base support which does not
require and use the crypto API and thus would require its own ACVTS testing).

Ciao
Stephan

**Comment by smuellerDD** [comment]
Issue has been clarified.
