### ISSUE TITLE
FIPS_dsa_generate_pq function definition missing

### ISSUE THREAD

**Issue by shilpa-1992** [smuellerDD/acvpparser#15]
i tried integrating the acvpparser tool to my openssl 1.0.2 with oopenssl-fips-2.0.16. And i am facing issue like FIPS_dsa_generate_pq ,FIPS_dsa_generate_g not available. 

May i know what exactly FIPS_dsa_generate_pq in backend_openssl.c

CKINT_O_LOG(FIPS_dsa_generate_pq(ctx, L, N,
 "FIPS_dsa_generate_pq() failed");
  "FIPS_dsa_generate_pq() failed %s\n",

**Comment by smuellerDD** [comment]
Am Dienstag, dem 20.04.2021 um 22:22 -0700 schrieb shilpa-1992:
> i tried integrating the acvpparser tool to my openssl 1.0.2 with oopenssl-
> fips-2.0.16. And i am facing issue like FIPS_dsa_generate_pq
> ,FIPS_dsa_generate_g not available.
> 
Enable the code path with FIPS_dsa_builtin_paramgen and replace the function
call with dsa_builtin_paramgen

That should do it.

Ciao
Stepahn
