### ISSUE TITLE
Question:Build issues with default openssl version

### ISSUE THREAD

**Issue by nidhidamodaran** [smuellerDD/acvpparser#16]
@smuellerDD , please list the openssl version requirement for make openssl command

**Comment by smuellerDD** [comment]
Am Donnerstag, dem 29.04.2021 um 23:01 -0700 schrieb Nidhi Damodaran:
> @smuellerDD , please list the openssl version requirement for make openssl
> command
> 
Fipsified OpenSSL 1.0.x, 1.1.x and OpenSSL 2.0.x should work.

**Comment by nidhidamodaran** [comment]
thanks @smuellerDD . i tried with fips 2.0.16 version, but it fails due to rand_drbg.h dependancy. Can you please share the openssl version link you are using

**Comment by smuellerDD** [comment]
Am Freitag, dem 30.04.2021 um 00:46 -0700 schrieb Nidhi Damodaran:
> thanks @smuellerDD . i tried with fips 2.0.16 version, but it fails due to
> rand_drbg.h dependancy. Can you please share the openssl version link you
> are using
> 

Then disable OPENSSL_11X_UPSTREAM_DRBG and enable the code for OPENSSL_10X.
Ensure that all other defines for OpenSSL version >= 1.1.0 are disabled.
