### ISSUE TITLE
Safe primes response not generated (Null json.partial file )

### ISSUE THREAD

**Issue by shilpa-1992** [smuellerDD/acvpparser#18]
Hello Team,

I have tried to acvp-parserto run request for safe primes.  (safePrimes_keyGen (response.json file not gererated)
safePrimes_keyVer (response.json file not gererated).

I have made few modification to backend_openssl.c for the build. 
Could you please clarify me the code part which takes the call for safeprimes ( code part necessary for the response generation of safe prime).

Regards,

**Comment by shilpa-1992** [comment]
/*
	 * TODO change to
	 * BIGNUM *BN_get_rfc3526_prime_2048(BIGNUM *bn);
	 * BIGNUM *BN_get_rfc3526_prime_3072(BIGNUM *bn);
	 * BIGNUM *BN_get_rfc3526_prime_4096(BIGNUM *bn);
	 * BIGNUM *BN_get_rfc3526_prime_6144(BIGNUM *bn);
	 * BIGNUM *BN_get_rfc3526_prime_8192(BIGNUM *bn);
	 */
Could you please let me know the relevance of this code part.

Regards,

**Comment by smuellerDD** [comment]
Am Montag, dem 10.05.2021 um 22:11 -0700 schrieb shilpa-1992:
> /*
>          * TODO change to
>          * BIGNUM *BN_get_rfc3526_prime_2048(BIGNUM *bn);
>          * BIGNUM *BN_get_rfc3526_prime_3072(BIGNUM *bn);
>          * BIGNUM *BN_get_rfc3526_prime_4096(BIGNUM *bn);
>          * BIGNUM *BN_get_rfc3526_prime_6144(BIGNUM *bn);
>          * BIGNUM *BN_get_rfc3526_prime_8192(BIGNUM *bn);
>          */
> Could you please let me know the relevance of this code part.

Some distros provide OpenSSL with those APIs making the safeprimes directly
accessible instead of adding the PQG values. But this is currently not present
in all OpenSSL versions.
> 
> Regards,
> 
>

**Comment by shilpa-1992** [comment]
ACVPParser (23:29:56) Error: DSA_generate_key() failed
ACVPParser (23:29:56) Error: Test execution failed
ACVPParser (23:29:56) Error: Parsing processdata failed

Above log is observed. Any clue what might have caused the failure.
testvector-response.json is with partial output

Regards,

**Comment by smuellerDD** [comment]
Am Dienstag, dem 11.05.2021 um 11:05 -0700 schrieb shilpa-1992:
> ACVPParser (23:29:56) Error: DSA_generate_key() failed

This is the issue. -vvv should give you more. If not, add
ERR_error_string(ERR_get_error(), NULL) to the log to see why OpenSSL is
unhappy.

But when you use such an old OpenSSL library version (FIPS 2.0.16), it is very
much possible that the DSA operation cannot handle safe primes.

Ciao
Stephan

> ACVPParser (23:29:56) Error: Test execution failed
> ACVPParser (23:29:56) Error: Parsing processdata failed
> 
> Above log is observed. Any clue what might have caused the failure.
> testvector-response.json is with partial output
> 
> Regards,
>  
>

**Comment by shilpa-1992** [comment]
In my openssl  APIs making the safeprimes directly accessible instead of adding the PQG values .
 so i have  enabled the below code part
 
           BIGNUM *BN_get_rfc3526_prime_2048(BIGNUM *bn);
           BIGNUM *BN_get_rfc3526_prime_3072(BIGNUM *bn);
           BIGNUM *BN_get_rfc3526_prime_4096(BIGNUM *bn);
           BIGNUM *BN_get_rfc3526_prime_6144(BIGNUM *bn);
           BIGNUM *BN_get_rfc3526_prime_8192(BIGNUM *bn);

Please let me know what all are the changes need to make in code to the values from bn above.

**Comment by smuellerDD** [comment]
Am Montag, dem 17.05.2021 um 05:06 -0700 schrieb shilpa-1992:
> In my openssl  APIs making the safeprimes directly accessible instead of
> adding the PQG values .
>  so i have  enabled the below code part
>  
>            BIGNUM *BN_get_rfc3526_prime_2048(BIGNUM *bn);
>            BIGNUM *BN_get_rfc3526_prime_3072(BIGNUM *bn);
>            BIGNUM *BN_get_rfc3526_prime_4096(BIGNUM *bn);
>            BIGNUM *BN_get_rfc3526_prime_6144(BIGNUM *bn);
>            BIGNUM *BN_get_rfc3526_prime_8192(BIGNUM *bn);
> 
> Please let me know what all are the changes need to make in code to the
> values from bn above.
> 
> 
> 

The backend code contains a marker where those should replace the call to the
parser-internal safeprime calls.

**Comment by shilpa-1992** [comment]
It is not clear to me , could you please explain a bit more.

**Comment by smuellerDD** [comment]
Am Montag, dem 17.05.2021 um 05:27 -0700 schrieb shilpa-1992:
> It is not clear to me , could you please explain a bit more.
> 
        /*
         * TODO change to
         * BIGNUM *BN_get_rfc3526_prime_2048(BIGNUM *bn);
         * BIGNUM *BN_get_rfc3526_prime_3072(BIGNUM *bn);
         * BIGNUM *BN_get_rfc3526_prime_4096(BIGNUM *bn);
         * BIGNUM *BN_get_rfc3526_prime_6144(BIGNUM *bn);
         * BIGNUM *BN_get_rfc3526_prime_8192(BIGNUM *bn);
         */
..
        } else {
                struct safeprimes *p_safeprime;

                CKINT(acvp_safeprime_get(safeprime, &p_safeprime));

                CKINT_O0(BN_hex2bn(&p, p_safeprime->p));
                CKINT_O0(BN_hex2bn(&q, p_safeprime->q));
                CKINT_O0(BN_hex2bn(&g, p_safeprime->g));

-> get p, g, q from the OpenSSL API

**Comment by shilpa-1992** [comment]
"-> get p, g, q from the OpenSSL API " with below code part will that happen or am i missing somthing  ( do i need to add something more here)

         * BIGNUM *BN_get_rfc3526_prime_2048(BIGNUM *bn);
         * BIGNUM *BN_get_rfc3526_prime_3072(BIGNUM *bn);
         * BIGNUM *BN_get_rfc3526_prime_4096(BIGNUM *bn);
         * BIGNUM *BN_get_rfc3526_prime_6144(BIGNUM *bn);
         * BIGNUM *BN_get_rfc3526_prime_8192(BIGNUM *bn);
                struct safeprimes *p_safeprime;

                CKINT(acvp_safeprime_get(safeprime, &p_safeprime));

                CKINT_O0(BN_hex2bn(&p, p_safeprime->p));
                CKINT_O0(BN_hex2bn(&q, p_safeprime->q));
                CKINT_O0(BN_hex2bn(&g, p_safeprime->g));

**Comment by smuellerDD** [comment]
Am Montag, dem 17.05.2021 um 05:38 -0700 schrieb shilpa-1992:
> "-> get p, g, q from the OpenSSL API " with below code part will that happen
> or am i missing somthing  ( do i need to add something more here)

There should nothing else be needed apart from this replacement.

**Comment by shilpa-1992** [comment]
For the same test vector i have run more than once and i could see that the ephemeralPublicIutX ,ephemeralPublicIutY and z is different , is that the expected . Any clue, what might have caused this.

**Comment by smuellerDD** [comment]
Am Montag, dem 17.05.2021 um 06:54 -0700 schrieb shilpa-1992:
> For the same test vector i have run more than once and i could see that the
> ephemeralPublicIutX ,ephemeralPublicIutY and z is different , is that the
> expected . Any clue, what might have caused this.
> 

Checking the test specification gives hints and considering DH_generate_key.
