### ISSUE TITLE
KAS_ECC full public key validation 

### ISSUE THREAD

**Issue by Nagarjuna-jantali** [smuellerDD/acvpparser#19]
Hello,

Does openssl backend support generating response for KAS-ECC full public key validation ?

Regards,
Nag

**Comment by smuellerDD** [comment]
Am Mittwoch, dem 12.05.2021 um 03:31 -0700 schrieb Nagarjun:
> Hello,
> 
> Does openssl backend support generating response for KAS-ECC full public key
> validation ?

Yes
> 
> Regards,
> Nag  
>
