### ISSUE TITLE
Accessing 1 test instance from JSON request file

### ISSUE THREAD

**Issue by amrithathorath** [smuellerDD/acvpparser#2]
Hi,
I'm updating the parser code so that I can access each test instance so that I can pass it to my back end implementation to perform necessary operations. I'm using the json-c code which is within the parser directory. Shown my code and error below:

I see the following error:

```
Program received signal SIGSEGV, Segmentation fault.
0x0000000000416502 in json_object_iter_begin (obj=0x6ba3f0) at /home/amritha/new_parser/code/commander/parsers/parse-json/json-c/json_object_iterator.c:74
74          iter.opaque_ = pTable->head;
```

My code is shown below:

```
struct json_object *in = NULL;
struct json_object_iterator it = json_object_iter_init_default();
struct json_object_iterator itEnd = json_object_iter_init_default();

json_read_data(filename, &in); // JSON object stored in json_object type

it = json_object_iter_begin(in); // point to first item
itEnd = json_object_iter_end(in); // point to last item

while (!json_object_iter_equal(&it, &itEnd)) {
       printf("%s\n", json_object_iter_peek_name(&it));
       json_object_iter_next(&it);
      }
```

I'm trying to extract 1 instance at a time from the request file (this is SHA):

```
{
      "tcId" : 1,
      "msg" : "A6",
      "len" : 8
}
```

I'm trying to populate my structure with msg and len values.

**Comment by smuellerDD** [comment]
Am Freitag, 4. Januar 2019, 16:38:56 CET schrieb amy123:

Hi amy123,

> I'm trying to populate my structure with msg and len values.

I am not sure what you really want to achieve. You should never touch JSON 
data structures or JSON code to begin with. All you need is to implement your 
backend using the C data structures defined in the various parser*.h files.

Ciao
Stephan

**Comment by amrithathorath** [comment]
Stephan,

Here is a background of what I'm trying to do.

1. I've 2 parts, the server side and client side.
    Client side is the code that performs crypto function. And this can be in Java or C or C++ or C#.
    Server side is the C code that (as of now) reads the .req files we get from NIST and extract values and 
    populate a structure and pass over the structure to client side to perform crypto operations.
2. I want to use the ACVP parser on the server side to just read the values and populate the structure and 
   not perform any crypto functions.

**Comment by amrithathorath** [comment]
Please correct me if I'm wrong.
In my code, this is what I've got (doing it only for SHA for now):

`json_read_data(filename, &in)   // This successfully loads json in "in".`

parser_sha.c has sha_tester() which has:

`struct sha_data vector;   // I'm assuming this is the struct you were referring to?`

So I call these 2 functions in my code after which I should be able to access the struct. Is that correct?

```
json_read_data(filename, &in) ;
sha_tester();
```
Thanks a lot for being so patient with me!

**Comment by smuellerDD** [comment]
Am Dienstag, 8. Januar 2019, 15:55:49 CET schrieb amy123:

Hi amy123,

> Please correct me if I'm wrong.
> In my code, this is what I've got (doing it only for SHA for now):

I am not sure what you want to achieve? You want to parse the JSON data 
youself? Go ahead and get the JSON parser of your choice and parse the entire 
JSON data yourself.

What the ACVP Parser does is outlined in the README:

"""
Architecture
------------

The parser consists of 3 layers:

1. parser.c implements a linked list where all parsers with usable
   callbacks are registered. Each parser must register with a particular 
cipher
   identifier. When a JSON file is parsed, the cipher identifier is searched 
for
   and the respective parser handler is called if a match is found.

2. parser_*.c implement the register functions registering with parser.c
   In addition, they implement the handler function that is triggered when
   parser.c is finished. The idea now is that the respective parser is invoked
   with the JSON file it can handle. The parser now implements all logic to:

        * parse the JSON file

        * obtain all relevant data from the JSON file and store it in a parser
          specific data structure

        * invoke the backend implementation that interfaces with the cipher
          mechanism implementation

        * create the JSON response file with the correct format.

3. backend_*.c implement the backend that uses the parser data structure to
   invoke a specific crypto library. The backend is not needed to implement 
all
   backend functions of all parsers. If a callback from a parser is not
   supported, it must be marked as NULL. If a parser identifies a NULL 
handler,
   it returns with an error such that the JSON file cannot be processed.
"""

If you want to extend it such that you link you own implementations with it, 
the README says:

"""
Backend Implementation
======================

A backend is the code that connects the parser with a particular cryptographic
implementation. A backend implements the code that invokes the cryptographic
implementation to be tested using the data provided with various data
structures.

The backend implementation is invoked once for each individual cipher test.
It does not need to carry state information other than what is required
by the particular cryptographic implementation it interfaces with.

The backend is unrelated to any formatting or other CAVS/ACVP logic.

A backend implementation is achieved with the following steps:

1. Include `backend_common.h` from the parser. There are no other header files
   from the parser needed. The `backend_common.h includes the various header
   files of the different parsers for the cipher implementations.

2. Select which cipher implementations the backend shall handle. For each
   cipher implementation, there is a `parser_*.h` header that defines the
   data structure(s) used to exchange data between the parser and the backend
   as well as the interface functions that need to be implemented by the
   backend. For the following example, a SHA hash implementation shall be
   tested. The corresponding header file is `parser_sha.h` which contains
   the `struct sha_data` definition. The documentation explains which member
   variables are provided by the parser and which data is expected to be
   returned by the backend. Furthermore, the `parser_sha.h` header defines
   the `struct sha_backend` function pointer data structure that must be
   filled by the backend.

3. The backend implements the functions defined by the function pointer data
   structure. In case of SHA, the `hash_generate` function must be implemented
   following the definition of the function in `parser_sha.h`.

4. The backend must now register its implementation by defining the function
   pointer data structure and registering it with the register call found
   in `parser_sha.h`. The function pointer data structure instance must
   be marked with the `ACVP_DEFINE_CONSTRUCTOR` macro to ensure that it is
   invoked by the operating system loader during load time of the executable.
   The following example illustrates this registering:

   ```
   static int backend_sha_generate(struct sha_data *data, flags_t 
parsed_flags)
   {
   ...
           <invoke the backend's SHA function>;
   ....
   }

   static struct sha_backend backend_sha =
   {
            backend_sha_generate,
   };

   ACVP_DEFINE_CONSTRUCTOR(backend_sha_backend)
   static void backend_sha_backend(void)
   {
            register_sha_impl(&backend_sha);
   }
   ```

5. Ensure that the C file(s) implementing the backend is compiled when 
compiling
   the parser.

The example outlines that apart from including the `backend_common.h`, no
further change is needed to link the backend implementation with the parser.

Note, the parser will guarantee that only one backend can register its 
callback
function pointer data structure for a given cipher. I.e. the function
`register_sha_impl` used in the example above MUST ONLY be used once in the
entire code base of the parser that is compiled. Subsequent register 
operations
for a particular cipher type will fail.
"""

The file backends/backend_openssl.c you find in the repository is such a 
backend linking the OpenSSL library with the parser. Use it as an example and 
see the large documentation in the parser/parser_*.h files.

Ciao
Stephan
