### ISSUE TITLE
Funtion flow for testType: AFT , KeyGen

### ISSUE THREAD

**Issue by shilpa-1992** [smuellerDD/acvpparser#20]
Vector set ID 556101 safePrimes           keyGen           FAILED
     Vector set ID 556103 KAS-FFC-SSC          -                FAILED

Could see that  "testType": "AFT", Failed in all cases.

What does this Meta info "AFT" say ?

"result": "failed",
"reason": "Z does not match"

Any clue on this failure situation.
what might have failed all the KeyGen .

Could you please share the function flow  "testType": "AFT".

 I understood that for key gen " _openssl_dh_keygen which calls openssl_dh_set_param to fill the DH structure with PQG and then call DH_generate_key to generate the key"

Regards,

**Comment by shilpa-1992** [comment]
envstr = secure_getenv("OPENSSL_ACVP_DH_KEYGEN");

Could you please brief how this string get set.

**Comment by smuellerDD** [comment]
Am Montag, dem 17.05.2021 um 02:53 -0700 schrieb shilpa-1992:
> envstr = secure_getenv("OPENSSL_ACVP_DH_KEYGEN");
> 
> Could you please brief how this string get set.
> 

See helper/exec_openssl.sh

**Comment by shilpa-1992** [comment]
What i understood is that through this script the Environment variable evaluated by ACVP Parser is set.

Currently i was executing the tool directly as "./acvp-parser <path>/testvector-request.json <path>/testvector-response.json

How to include the helper script as well in execution , is it necessary to include the helper script.

Regards,

**Comment by smuellerDD** [comment]
Am Montag, dem 17.05.2021 um 03:23 -0700 schrieb shilpa-1992:
> What i understood is that through this script the Environment variable
> evaluated by ACVP Parser is set.
> 
> Currently i was executing the tool directly as "./acvp-parser
> <path>/testvector-request.json <path>/testvector-response.json
> 
> How to include the helper script as well in execution , is it necessary to
> include the helper script.

The script is intended to automate running hundreds of test vectors
automatically with the right options.

If you invoke testing manually you need to set the environment variable as
needed for your command.

Ciao
Stephan
> 
> Regards,
> 
>
