### ISSUE TITLE
Cannot build for libkcapi

### ISSUE THREAD

**Issue by tiendatnt** [smuellerDD/acvpparser#21]
Hi there,

I check here [http://www.chronox.de/acvpparser.html](url) and see that the libkcapi was successfully linked with and tested using the ACVP Parser. I tried to build the parser for libkcapi with the below command:
`make libkcapi`

However, It was failed:
> make: *** No rule to make target 'backends/backend_libkcapi.c', needed by 'backends/backend_libkcapi.o'. Stop.

I checked the backends directory and there is no `backends/backend_libkcapi.c`.
May I ask some questions:
1. Is the `backends/backend_libkcapi.c` necessary?
2. If (1) is YES, is the backend open source?
3. If (2) is NO, could you please give me some hints to implement the backend?

Waiting for your response.
Thank you and Best Regards,

**Comment by smuellerDD** [comment]
Am Samstag, dem 15.05.2021 um 18:17 -0700 schrieb tiendatnt:
> Hi there,
> 
> I check here [http://www.chronox.de/acvpparser.html](url) and see that the
> libkcapi was successfully linked with and tested using the ACVP Parser. I
> tried to build the parser for libkcapi with the below command:
> `make libkcapi`
> 
> However, It was failed:
> > make: *** No rule to make target 'backends/backend_libkcapi.c', needed by
> > 'backends/backend_libkcapi.o'. Stop.
> 
> I checked the backends directory and there is no
> `backends/backend_libkcapi.c`.
> May I ask some questions:
> 1. Is the `backends/backend_libkcapi.c` necessary?

Yes, the backend is the link between the parser's filled C data structures and
the actual crypto library.

> 2. If (1) is YES, is the backend open source?

It is not open source. It is available to customers of the company I work for.

> 3. If (2) is NO, could you please give me some hints to implement the
> backend?

See README.md sectino Backend Implementation

Ciao
Stephan
> 
> Waiting for your response.
> Thank you and Best Regards,
>

**Comment by tiendatnt** [comment]
Hi Stephan,
Thank you for your reply.
I got it.

By the way, I also checked version 2.1.2 that released yesterday,
I think that the kcapi-lrng backend can also be used for testing Linux Kernel Crypto module algorithms.
I used the kcapi-lrng backend to test AES, HMAC, and SHA algorithms implemented by the Linux Kernel Crypto module. It's OK.
Thank you.
