### ISSUE TITLE
When I use acvpparser to process json file, but it does not work 

### ISSUE THREAD

**Issue by ShowKnight** [smuellerDD/acvpparser#22]
[root@3108f4151d10 acvpparser-2.1.0]  ./acvp-parser simple.json exp.json -v
**ACVPParser (15:25:30) Warning: No data found in ACVP server response: [**
  {
    "jwt":"6a393a1a14c8f59d032ea353c7931e64c7722cc1ddb3003a4e2a3a1f9acbade1dd42048804458736061f5decb98fc8540bdb4aef89a2f9eee490c8a4b7806f2e06a1807950094e9ff913f20a36c73a2ff5aaafc6adbf2ea5c359b29e640ddd73ac8e0441b4c83c2b122cb5506e6abc8d268803971d784b3b495eb7465d9b624b1f03b4c673ad94865da26e93cebcdcc0286f2354c08c98fdf9051bba28a7f2af91557e3aa4b1496713ce38eea3c14081565fd24fab0b14b614632efa56f145c845deee6a73a9f12551cf6a5255a5105e1d1d19d8073962d065ded9d6657bcf48bc4e462a765a96b6beaed74827fb5a1f17393d949546ae505bcb096a9ceaa240b83d3320fc7c89733bf1a7e18b5ac8a931a7c5cfa5530a0f77516d13e68dc88ac1c82ec4ee85ec753b8cd288fd0fdc66b37d773d3c8a1e80e14c36913109478c3f60cd9ffee0ca8eb4d62c8ad1b5e8363bc8da83da3a132994a111360c6792f950f42865a6f3a9cf366c3319ed1b29a8e0341c2edf54ba9e9cf8e5c5683ea9ddff2ab22001d82554adc6d7fa324623adab452b6765a59d68fea20a60a78438f638782c9e33c5d2372a933b5b393b5be66cd32b84894405c2bb537df96477d937625dc6c14f776a2345",
    "url":"\/acvp\/v1\/testSessions\/178363",
    "vectorSetUrls":[
      "\/acvp\/v1\/testSessions\/178363\/vectorSets\/562951"
    ]
  },
  {
    "vsId":562948,
    "algorithm":"ACVP-AES-ECB",
    "revision":"1.0",
    "isSample":true,
    "testGroups":[
      {
        "tgId":1,
        "testType":"AFT",
        "direction":"encrypt",
        "keyLen":256,
        "tests":[
          {
            "tcId":1,
            "pt":"014730F80AC625FE84F026C60BFD547D",
            "key":"0000000000000000000000000000000000000000000000000000000000000000"
          },
          {
            "tcId":2,
            "pt":"0B24AF36193CE4665F2825D7B4749C98",
            "key":"0000000000000000000000000000000000000000000000000000000000000000"
          },
          {
            "tcId":3,
            "pt":"761C1FE41A18ACF20D241650611D90F1",
            "key":"0000000000000000000000000000000000000000000000000000000000000000"
          },
          {
            "tcId":4,
            "pt":"8A560769D605868AD80D819BDBA03771",
            "key":"0000000000000000000000000000000000000000000000000000000000000000"
          },
          {
            "tcId":5,
            "pt":"91FBEF2D15A97816060BEE1FEAA49AFE",
            "key":"0000000000000000000000000000000000000000000000000000000000000000"
          }
        ]
      },
      {
        "tgId":2,
        "testType":"AFT",
        "direction":"encrypt",
        "keyLen":256,
        "tests":[
          {
            "tcId":6,
            "pt":"00000000000000000000000000000000",
            "key":"C47B0294DBBBEE0FEC4757F22FFEEE3587CA4730C3D33B691DF38BAB076BC558"
          },
          {
            "tcId":7,
            "pt":"00000000000000000000000000000000",
            "key":"28D46CFFA158533194214A91E712FC2B45B518076675AFFD910EDECA5F41AC64"
          },
          {
            "tcId":8,
            "pt":"00000000000000000000000000000000",
            "key":"C1CC358B449909A19436CFBB3F852EF8BCB5ED12AC7058325F56E6099AAB1A1C"
          },
          {
            "tcId":9,
            "pt":"00000000000000000000000000000000",
            "key":"984CA75F4EE8D706F46C2D98C0BF4A45F5B00D791C2DFEB191B5ED8E420FD627"
          },
          {
            "tcId":10,
            "pt":"00000000000000000000000000000000",
            "key":"1D85A181B54CDE51F0E098095B2962FDC93B51FE9B88602B3F54130BF76A5BD9"
          },
          {
            "tcId":11,
            "pt":"00000000000000000000000000000000",
            "key":"797F8B3D176DAC5B7E34A2D539C4EF367A16F8635F6264737591C5C07BF57A3E"
          },
          {
            "tcId":12,
            "pt":"00000000000000000000000000000000",
            "key":"13428B5E4C005E0636DD338405D173AB135DEC2A25C22C5DF0722D69DCC43887"
          },
          {
            "tcId":13,
            "pt":"00000000000000000000000000000000",
            "key":"B43D08A447AC8609BAADAE4FF12918B9F68FC1653F1269222F123981DED7A92F"
          },
          {
            "tcId":14,
            "pt":"00000000000000000000000000000000",
            "key":"797F8B3D176DAC5B7E34A2D539C4EF367A16F8635F6264737591C5C07BF57A3E"
          },

[root@3108f4151d10 acvpparser-2.1.0] echo $?
22

My origin file is as this , Can you give me some clue to solve it?  
[req.zip](https://github.com/smuellerDD/acvpparser/files/6639526/req.zip)

**Comment by ShowKnight** [comment]
I have try my best to sovle the compile f problem, but it can't process the json file,I feel so sorry..

**Comment by smuellerDD** [comment]
Am Freitag, dem 11.06.2021 um 08:29 -0700 schrieb Knight:
> ***@***.*** acvpparser-2.1.0]  ./acvp-parser simple.json exp.json -v
> **ACVPParser (15:25:30) Warning: No data found in ACVP server response: [**
>   {
>    
> "jwt":"6a393a1a14c8f59d032ea353c7931e64c7722cc1ddb3003a4e2a3a1f9acbade1dd420
> 48804458736061f5decb98fc8540bdb4aef89a2f9eee490c8a4b7806f2e06a1807950094e9ff
> 913f20a36c73a2ff5aaafc6adbf2ea5c359b29e640ddd73ac8e0441b4c83c2b122cb5506e6ab
> c8d268803971d784b3b495eb7465d9b624b1f03b4c673ad94865da26e93cebcdcc0286f2354c
> 08c98fdf9051bba28a7f2af91557e3aa4b1496713ce38eea3c14081565fd24fab0b14b614632
> efa56f145c845deee6a73a9f12551cf6a5255a5105e1d1d19d8073962d065ded9d6657bcf48b
> c4e462a765a96b6beaed74827fb5a1f17393d949546ae505bcb096a9ceaa240b83d3320fc7c8
> 9733bf1a7e18b5ac8a931a7c5cfa5530a0f77516d13e68dc88ac1c82ec4ee85ec753b8cd288f
> d0fdc66b37d773d3c8a1e80e14c36913109478c3f60cd9ffee0ca8eb4d62c8ad1b5e8363bc8d
> a83da3a132994a111360c6792f950f42865a6f3a9cf366c3319ed1b29a8e0341c2edf54ba9e9
> cf8e5c5683ea9ddff2ab22001d82554adc6d7fa324623adab452b6765a59d68fea20a60a7843
> 8f638782c9e33c5d2372a933b5b393b5be66cd32b84894405c2bb537df96477d937625dc6c14
> f776a2345",
>     "url":"\/acvp\/v1\/testSessions\/178363",
>     "vectorSetUrls":[
>       "\/acvp\/v1\/testSessions\/178363\/vectorSets\/562951"
>     ]
>   },

That is the problem - this data is added by the tool you used to download the
test vector (libacvp most likely). This data is not part of the ACVP-Server-
provided data. The parser is only able to operate on the data provided by the
server.

That said, remove this part and it should work.


>   {
>     "vsId":562948,
>     "algorithm":"ACVP-AES-ECB",
>     "revision":"1.0",
>     "isSample":true,
>     "testGroups":[
>       {
>         "tgId":1,
>         "testType":"AFT",
>         "direction":"encrypt",
>         "keyLen":256,
>         "tests":[
>           {
>             "tcId":1,
>             "pt":"014730F80AC625FE84F026C60BFD547D",
>            
> "key":"0000000000000000000000000000000000000000000000000000000000000000"
>           },
>           {
>             "tcId":2,
>             "pt":"0B24AF36193CE4665F2825D7B4749C98",
>            
> "key":"0000000000000000000000000000000000000000000000000000000000000000"
>           },
>           {
>             "tcId":3,
>             "pt":"761C1FE41A18ACF20D241650611D90F1",
>            
> "key":"0000000000000000000000000000000000000000000000000000000000000000"
>           },
>           {
>             "tcId":4,
>             "pt":"8A560769D605868AD80D819BDBA03771",
>            
> "key":"0000000000000000000000000000000000000000000000000000000000000000"
>           },
>           {
>             "tcId":5,
>             "pt":"91FBEF2D15A97816060BEE1FEAA49AFE",
>            
> "key":"0000000000000000000000000000000000000000000000000000000000000000"
>           }
>         ]
>       },
>       {
>         "tgId":2,
>         "testType":"AFT",
>         "direction":"encrypt",
>         "keyLen":256,
>         "tests":[
>           {
>             "tcId":6,
>             "pt":"00000000000000000000000000000000",
>            
> "key":"C47B0294DBBBEE0FEC4757F22FFEEE3587CA4730C3D33B691DF38BAB076BC558"
>           },
>           {
>             "tcId":7,
>             "pt":"00000000000000000000000000000000",
>            
> "key":"28D46CFFA158533194214A91E712FC2B45B518076675AFFD910EDECA5F41AC64"
>           },
>           {
>             "tcId":8,
>             "pt":"00000000000000000000000000000000",
>            
> "key":"C1CC358B449909A19436CFBB3F852EF8BCB5ED12AC7058325F56E6099AAB1A1C"
>           },
>           {
>             "tcId":9,
>             "pt":"00000000000000000000000000000000",
>            
> "key":"984CA75F4EE8D706F46C2D98C0BF4A45F5B00D791C2DFEB191B5ED8E420FD627"
>           },
>           {
>             "tcId":10,
>             "pt":"00000000000000000000000000000000",
>            
> "key":"1D85A181B54CDE51F0E098095B2962FDC93B51FE9B88602B3F54130BF76A5BD9"
>           },
>           {
>             "tcId":11,
>             "pt":"00000000000000000000000000000000",
>            
> "key":"797F8B3D176DAC5B7E34A2D539C4EF367A16F8635F6264737591C5C07BF57A3E"
>           },
>           {
>             "tcId":12,
>             "pt":"00000000000000000000000000000000",
>            
> "key":"13428B5E4C005E0636DD338405D173AB135DEC2A25C22C5DF0722D69DCC43887"
>           },
>           {
>             "tcId":13,
>             "pt":"00000000000000000000000000000000",
>            
> "key":"B43D08A447AC8609BAADAE4FF12918B9F68FC1653F1269222F123981DED7A92F"
>           },
>           {
>             "tcId":14,
>             "pt":"00000000000000000000000000000000",
>            
> "key":"797F8B3D176DAC5B7E34A2D539C4EF367A16F8635F6264737591C5C07BF57A3E"
>           },
> 
> 
> 
> ***@***.*** acvpparser-2.1.0] echo $?
> 22
> 
> My origin file is as this , Can you give me some clue to solve it?  
> [req.zip](https://github.com/smuellerDD/acvpparser/files/6639526/req.zip)
> 
> 
>

**Comment by ShowKnight** [comment]
It does not work when I remove the part, can you take a try?
[req_del_something.zip](https://github.com/smuellerDD/acvpparser/files/6647198/req_del_something.zip)

**Comment by smuellerDD** [comment]
Am Montag, dem 14.06.2021 um 02:26 -0700 schrieb Knight:
> It does not work when I remove the part, can you take a try?
> [req_del_something.zip](https://github.com/smuellerDD/acvpparser/files/6647198/req_del_something.zip
> )
> 
> 
> 
You need to get the official ACVP JSON structure. This is as follows for your
file:

[
  {
    "acvVersion": "1.0"
  },
   {
      "vsId": 562948,
      "algorithm": "AES-ECB",
      "revision": "1.0",
      "isSample": true,
      "testGroups": [
         {
            "tgId": 1,
            "testType": "AFT",
            "direction": "encrypt",
            "keyLen": 256,
            "tests": [
               {
                  "tcId": 1,
                  "pt": "014730F80AC625FE84F026C60BFD547D",
                  "key":
"0000000000000000000000000000000000000000000000000000000000000000"
               },
...

Then it works.

Ciao
Stephan

**Comment by ShowKnight** [comment]
Thanks,  it works! 

It seems only one problem left:
When I use this method to process one json file, but has error like this, Did it have happened to you ?
[root@3108f4151d10 acvpparser-2.1.0]# ./acvp-parser  req_error.json  test3.json -v
ACVPParser (13:43:07) Error: JSON data type object does not match expected type array for field largeMsg
ACVPParser (13:43:07) Error: Name largeMsg not found
ACVPParser (13:43:07) Warning: Searched object: largeMsg
ACVPParser (13:43:07) Error: Parsing processdata failed
ACVPParser (13:43:07) Warning: Searched object: tests
ACVPParser (13:43:07) Error: Parsing processdata failed
ACVPParser (13:43:07) Warning: Searched object: testGroups

Seems like this part can not be processed:
            "testType": "LDT",
            "tests": [
               {
                  "tcId": 514,
                  "largeMsg": {
                     "content": "9059809B401F934A",
                     "contentLength": 64,
                     "fullLength": 8589934592,
                     "expansionTechnique": "repeating"
                  }
               },
               {
                  "tcId": 515,
                  "largeMsg": {
                     "content": "F6AB0539F4DAC50E",
                     "contentLength": 64,
                     "fullLength": 17179869184,
                     "expansionTechnique": "repeating"
                  }
               }

file is below here:
[req_error.zip](https://github.com/smuellerDD/acvpparser/files/6648694/req_error.zip)

**Comment by smuellerDD** [comment]
Am Montag, dem 14.06.2021 um 06:51 -0700 schrieb Knight:
> Thanks,  it works! 
> 
> It seems only one problem left:
> When I use this method to process one json file, but has error like this,
> Did it have happened to you ?
> ***@***.*** acvpparser-2.1.0]# ./acvp-parser  req_error.json 
> test3.json -v
> ACVPParser (13:43:07) Error: JSON data type object does not match expected
> type array for field largeMsg

Ah, the largeMsg - I actually have to admit that I did not fully test it yet.

Send me the file and I can have a look.

Ciao
Stephan

> ACVPParser (13:43:07) Error: Name largeMsg not found
> ACVPParser (13:43:07) Warning: Searched object: largeMsg
> ACVPParser (13:43:07) Error: Parsing processdata failed
> ACVPParser (13:43:07) Warning: Searched object: tests
> ACVPParser (13:43:07) Error: Parsing processdata failed
> ACVPParser (13:43:07) Warning: Searched object: testGroups
> 
> Seems like this part can not be processed:
>             "testType": "LDT",
>             "tests": [
>                {
>                   "tcId": 514,
>                   "largeMsg": {
>                      "content": "9059809B401F934A",
>                      "contentLength": 64,
>                      "fullLength": 8589934592,
>                      "expansionTechnique": "repeating"
>                   }
>                },
>                {
>                   "tcId": 515,
>                   "largeMsg": {
>                      "content": "F6AB0539F4DAC50E",
>                      "contentLength": 64,
>                      "fullLength": 17179869184,
>                      "expansionTechnique": "repeating"
>                   }
>                }
> 
> file is below here:
> [req_error.zip](
> https://github.com/smuellerDD/acvpparser/files/6648694/req_error.zip)
> 
>

**Comment by ShowKnight** [comment]
Thanks!
File is below here
[req_error.zip](https://github.com/smuellerDD/acvpparser/files/6649548/req_error.zip)

**Comment by smuellerDD** [comment]
Am Montag, dem 14.06.2021 um 08:34 -0700 schrieb Knight:
> Thanks!
> File is below here
> [req_error.zip](https://github.com/smuellerDD/acvpparser/files/6649548/req_error.zip
> )
> 
> 
Apply this patch.

**Comment by ShowKnight** [comment]
Hi, smuellerDD, do you have any update about this one?

**Comment by smuellerDD** [comment]
Am Sonntag, dem 20.06.2021 um 23:43 -0700 schrieb Knight:
> Hi, smuellerDD, do you have any update about this one?
> 
It seems the patch was not sent through by github. I have pushed the change.

Ciao
Stephan

**Comment by ShowKnight** [comment]
It works，thanks， smuellerDD！
