### ISSUE TITLE
openssh backend

### ISSUE THREAD

**Issue by Nagarjuna-jantali** [smuellerDD/acvpparser#24]
Hello,

I have downloaded the ssh kdf vector from the demo server:

   "algorithm": "kdf-components",
    "mode": "ssh",
    "revision": "1.0",
    "isSample": true,
    "testGroups": [
        {
            "tgId": 1,
            "cipher": "AES-128",
            "hashAlg": "SHA-1",
            "testType": "AFT",
            "tests": [
                {
                    "tcId": 1,
                    "k": "0000010100B6E7153B1AF462116B6D33F3689D0827B7A049370E76432408386EE068EA45B8FA3717FA93561CC3FF18ECF5054DDCC054AE0E10BA7100CEE2A99236B8622958633840455E5DD5C5B003A80F4425CE9B6E26439242A8F13B7C7558691CCDC7A827311BD4E84BE7984050B9ABAC7D443A13AE047F0B50897E0C289045F516166AAF558C8960E14973A64EE3CB27FE630DBB4E80323776FEB4BA7BB531BE8EE6231CE0AA108A008993E13CF6090544FAC25A4FD4DC3A334A59661789E9742BAF9D57E81021C0BE5D8F2BBA6582D064CC44652A5D6E2B3E0C2C016BCFE890B44D47BEC76DD18860ECB7BE001A465F4CC535FF199EC2726E65C5B99981AD761B8F45",
                    "h": "F26C9F7C7AC80976B1E044A452734524CA0177C9",
                    "sessionId": "E192D647BF44BF5C0FCD1D797E577ED88506CE7A"
                },

The vector does not contain IV length and encryption key length parameters , instead contain "cipher" field. Do not how to process the vector . Any input will be help full.

Thanks ,
Nag

**Comment by smuellerDD** [comment]
Am Dienstag, dem 15.06.2021 um 07:53 -0700 schrieb Nagarjun:
> Hello,
> 
> I have downloaded the ssh kdf vector from the demo server:
> 
>    "algorithm": "kdf-components",
>     "mode": "ssh",
>     "revision": "1.0",
>     "isSample": true,
>     "testGroups": [
>         {
>             "tgId": 1,
>             "cipher": "AES-128",
>             "hashAlg": "SHA-1",
>             "testType": "AFT",
>             "tests": [
>                 {
>                     "tcId": 1,
>                     "k":
> "0000010100B6E7153B1AF462116B6D33F3689D0827B7A049370E76432408386EE068EA45B8F
> A3717FA93561CC3FF18ECF5054DDCC054AE0E10BA7100CEE2A99236B8622958633840455E5DD
> 5C5B003A80F4425CE9B6E26439242A8F13B7C7558691CCDC7A827311BD4E84BE7984050B9ABA
> C7D443A13AE047F0B50897E0C289045F516166AAF558C8960E14973A64EE3CB27FE630DBB4E8
> 0323776FEB4BA7BB531BE8EE6231CE0AA108A008993E13CF6090544FAC25A4FD4DC3A334A596
> 61789E9742BAF9D57E81021C0BE5D8F2BBA6582D064CC44652A5D6E2B3E0C2C016BCFE890B44
> D47BEC76DD18860ECB7BE001A465F4CC535FF199EC2726E65C5B99981AD761B8F45",
>                     "h": "F26C9F7C7AC80976B1E044A452734524CA0177C9",
>                     "sessionId": "E192D647BF44BF5C0FCD1D797E577ED88506CE7A"
>                 },
> 
> 
> The vector does not contain IV length and encryption key length parameters ,
> instead contain "cipher" field. Do not how to process the vector . Any input
> will be help full.

You are supposed to generate the key, iv and mac key from k via the KDF.

See the documentation of struct kdf_ssh_data in the parser what is the input
and what is the expected output.

Ciao
Stephan
> 
> Thanks ,
> Nag
> 
>

**Comment by Nagarjuna-jantali** [comment]
resovled
