### ISSUE TITLE
openssh compilation error

### ISSUE THREAD

**Issue by Nagarjuna-jantali** [smuellerDD/acvpparser#25]
undefined reference to `kex_derive_keys_bn'
collect2: error: ld returned 1 exit status

"kex_derive_keys_bn" definition is missing , definition  is also  not present openssh code.

Thanks,
Nag

**Comment by smuellerDD** [comment]
Am Mittwoch, dem 16.06.2021 um 03:30 -0700 schrieb Nagarjun:
>  undefined reference to `kex_derive_keys_bn'
> collect2: error: ld returned 1 exit status
> 
> "kex_derive_keys_bn" definition is missing , definition  is also  not
> present openssh code.

Then the openssh backend is not what you need, but the openssl backend.
> 
> Thanks,
> Nag
> 
>

**Comment by Nagarjuna-jantali** [comment]
> Am Mittwoch, dem 16.06.2021 um 03:30 -0700 schrieb Nagarjun:
>  undefined reference to `kex_derive_keys_bn' collect2: error: ld returned 1 exit status "kex_derive_keys_bn" definition is missing , definition  is also  not present openssh code.
> Then the openssh backend is not what you need, but the openssl backend.
> […](#)
> Thanks, Nag

Hi,

 "kex_derive_keys_bn" function is removed from latest version of the openssh code . Was there is earlier version of openssh code.
I checked openssh-8.7 and openssh-7.7 code.

Thanks
Nag

**Comment by smuellerDD** [comment]
Am Mittwoch, dem 16.06.2021 um 06:24 -0700 schrieb Nagarjun:
> > Am Mittwoch, dem 16.06.2021 um 03:30 -0700 schrieb Nagarjun:
> >  undefined reference to `kex_derive_keys_bn' collect2: error: ld returned
> > 1 exit status "kex_derive_keys_bn" definition is missing , definition  is
> > also  not present openssh code.
> > Then the openssh backend is not what you need, but the openssl backend.
> > […](#)
> > Thanks, Nag
> 
> Hi,
> 
>  "kex_derive_keys_bn" function is removed from latest version of the openssh
> code . Was there is earlier version of openssh code.
> I checked openssh-8.7 and openssh-7.7 code.

So, it takes its KDF from OpenSSL which in turn needs to be tested
