### ISSUE TITLE
Public Availability of `acvp2cavs` and `cavs2acvp` backends

### ISSUE THREAD

**Issue by AlexThurston** [smuellerDD/acvpparser#3]
Out of curiosity (and perhaps I'm missing them and they're actually there) is there any intention in making the `acvp2cavs` or `cavs2acvp` backends public?  It seems like there are references to them in the `Makefile` and in some of the documentation but I can't seem to build them nor find their source files.

Thanks very much for your time.

**Comment by smuellerDD** [comment]
Am Mittwoch, 23. Oktober 2019, 20:49:47 CEST schrieb Alex Thurston:

Hi Alex,

> Out of curiosity (and perhaps I'm missing them and they're actually there)
> is there any intention in making the `acvp2cavs` or `cavs2acvp` backends
> public?  It seems like there are references to them in the `Makefile` and
> in some of the documentation but I can't seem to build them nor find their
> source files.
> 
> Thanks very much for your time.

Well, these two backends do exist here and are fully operational to convert 
ACVP to CAVS and back. Bot for now, there is no intention to release those 
converters as open source.

e do use them, however, with customers.

Ciao
Stephan
