### ISSUE TITLE
Create shared and static libraries of the acvpparser

### ISSUE THREAD

**Issue by DanielOjalvo** [smuellerDD/acvpparser#30]
Hi all,

We've been using the acvpparser framework to facilitate cavs testing using our existing code. In the course of doing this, I modified the Makefile and a few other files to add a makefile target to create shared and static libraries (libacvpparser.so and libacvpparser.a). I have a git repository with these changes, but I'm not sure how to push up my changes at this time. Does this need a new branch?

Thanks,
Dan

**Comment by smuellerDD** [comment]
When you fork from my master, you locally create a new branch and commit your changes. Then you send me a merge request via the github UI.

If it is easier, you can also locally create a branch, apply your changes and call `git format-patch master` and send me all files.

**Comment by smuellerDD** [comment]
Applied
