### ISSUE TITLE
acvp-parser not generating response for RSA_ sigGen

### ISSUE THREAD

**Issue by Nagarjuna-jantali** [smuellerDD/acvpparser#35]
Hello,

I am trying to generate response for RSA_sigGen, but getting this error. 

acvpparser-2.1.3$ ./acvp-parser  /home/nagarjun/openssl_sample_vect/651205\ RSA\ sigGen/testvector-request.json /home/nagarjun/openssl_sample_vect/651205\ RSA\ sigGen/testvector-response.json
ACVPParser (04:59:08) Error: EVP_DigestSignFinal failed: error:060A80A3:lib(6):func(168):reason(163)
ACVPParser (04:59:08) Error: Test execution failed
ACVPParser (04:59:08) Error: Parsing processdata failed

I am using FIPS openssl (1.0.2l+2.0.16)
acvpparser-2.1.3$ ldd acvp-parser 
	linux-vdso.so.1 (0x00007fff6b7ce000)
	libcrypto.so.1.0.0 => /home/nagarjun/unpatched_srccode/FIPS/usr/local/ssl/lib/libcrypto.so.1.0.0 (0x00007f4ea2f3e000)
	libssl.so.1.0.0 => /home/nagarjun/unpatched_srccode/FIPS/usr/local/ssl/lib/libssl.so.1.0.0 (0x00007f4ea2ccb000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f4ea28da000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f4ea26d6000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f4ea3656000)

Please let me know how to resolve this.

Thanks 
Nag

**Comment by smuellerDD** [comment]
Am Montag, dem 09.08.2021 um 06:07 -0700 schrieb Nagarjun:
> Hello,
> 
> I am trying to generate response for RSA_sigGen, but getting this error. 
> 
> acvpparser-2.1.3$ ./acvp-parser  /home/nagarjun/openssl_sample_vect/651205\
> RSA\ sigGen/testvector-request.json
> /home/nagarjun/openssl_sample_vect/651205\ RSA\ sigGen/testvector-
> response.json
> ACVPParser (04:59:08) Error: EVP_DigestSignFinal failed:
> error:060A80A3:lib(6):func(168):reason(163)

Here is the error - you need to check your library where that error is
generated and why it is generated. Perhaps it is some mismatching algorithm
options.

Ciao
Stephan

> ACVPParser (04:59:08) Error: Test execution failed
> ACVPParser (04:59:08) Error: Parsing processdata failed
> 
> I am using FIPS openssl (1.0.2l+2.0.16)
> acvpparser-2.1.3$ ldd acvp-parser 
>         linux-vdso.so.1 (0x00007fff6b7ce000)
>         libcrypto.so.1.0.0 =>
> /home/nagarjun/unpatched_srccode/FIPS/usr/local/ssl/lib/libcrypto.so.1.0.0
> (0x00007f4ea2f3e000)
>         libssl.so.1.0.0 =>
> /home/nagarjun/unpatched_srccode/FIPS/usr/local/ssl/lib/libssl.so.1.0.0
> (0x00007f4ea2ccb000)
>         libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f4ea28da000)
>         libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f4ea26d6000)
>         /lib64/ld-linux-x86-64.so.2 (0x00007f4ea3656000)
> 
> Please let me know how to resolve this.
> 
> Thanks 
> Nag
>
