### ISSUE TITLE
Botan Backend error

### ISSUE THREAD

**Issue by jasj23** [smuellerDD/acvpparser#39]
Hi , I get the following error:
make: *** No rule to make target 'backends/backend_botan.c', needed by 'backends/backend_botan.o'.  Stop.

Please where can i get the backend_botan.c file? 

Thanks

**Comment by jasj23** [comment]
Hi , I get the following error:
make: *** No rule to make target 'backends/backend_botan.c', needed by 'backends/backend_botan.o'. Stop.

Please where can i get the backend_botan.c file?

Thanks

**Comment by smuellerDD** [comment]
Am Montag, dem 30.08.2021 um 06:11 -0700 schrieb jasj23:
> Hi , I get the following error:
> make: *** No rule to make target 'backends/backend_botan.c', needed by
> 'backends/backend_botan.o'. Stop.
> 
> Please where can i get the backend_botan.c file?
> 
> Thanks
> 

The botan (and other backends) are proprietary. My company can offer you
assistance with testing botan.

Ciao
Stephan
