### ISSUE TITLE
Change bae9a02 missing files and cannot build

### ISSUE THREAD

**Issue by debrus** [smuellerDD/acvpparser#50]
I'm trying to build at tip and I'm getting errors complaining about missing includes.

Two that I know about are "parser_kdf_srtp.h" and "parser_cshake.h". There could be more I imagine.

Could you add the missing files please?

**Comment by smuellerDD** [comment]
Am Freitag, 17. Juni 2022, 01:50:29 CEST schrieb debrus:

Hi debrus,

> I'm trying to build at tip and I'm getting errors complaining about missing
> includes.
> 
> Two that I know about are "parser_kdf_srtp.h" and "parser_cshake.h". There
> could be more I imagine.
> 
> Could you add the missing files please?

Sorry, I forgot to git add them. They are now pushed.

Ciao
Stephan

**Comment by debrus** [comment]
Thanks, the extra commit solved the problem.
