### ISSUE TITLE
Is rsa is not one of the supported backends implementations for openssl3.

### ISSUE THREAD

**Issue by jbmukund** [smuellerDD/acvpparser#52]
I have a acvp parser built for openssl3 and I tried to pass a RSA request and it failed immediately.
A trace shows me it is failed here:
	main()
		perform_testing
			get_algorithm
			test_algo
				curr_tester->process_req(in, out, cipher);      // rsa_tester (parser/parser_rsa.c +682)
					logger(LOGGER_WARN, "No RSA backend set\n") // FAILs  (parser/parser_rsa.c +359)

Looks like RSA is not one of the supported backends implementations for openssl3.
Is that due? is there a reason it is not supported?

# grep "_backend(" backends/backend_openssl3.c
	static void openssl_mac_backend(void)
	static void openssl_kmac_backend(void)
	static void openssl_dh_backend(void)
	static void openssl_ecdh_backend(void)
	static void openssl_drbg_backend(void)
	static void openssl_kdf_tls_backend(void)
	static void openssl_kdf_ssh_backend(void)
	static void openssl_kdf_108_backend(void)
	static void openssl_dsa_backend(void)
	static void openssl_ecdsa_backend(void)

Please also find the detailed debug log attached.
[acvp-parser_openssl3-fails-to-process-RSA-Json-file.txt](https://github.com/smuellerDD/acvpparser/files/9153729/acvp-parser_openssl3-fails-to-process-RSA-Json-file.txt)

**Comment by smuellerDD** [comment]
Am Mittwoch, 20. Juli 2022, 20:55:04 CEST schrieb Mukund Jampala:

Hi Mukund,

> I have a acvp parser built for openssl3 and I tried to pass a RSA request
> and it failed immediately. A trace shows me it is failed here:
> 	main()
> 		perform_testing
> 			get_algorithm
> 			test_algo
> 				curr_tester->process_req(in, out, cipher);      // 
rsa_tester
> (parser/parser_rsa.c +682) logger(LOGGER_WARN, "No RSA backend set\n") //
> FAILs  (parser/parser_rsa.c +359)

There is on RSA backend published yet. There will be one soon.
> 
> Looks like RSA is not one of the supported backends implementations for
> openssl3. Is that due? is there a reason it is not supported?
> 
> # grep "_backend(" backends/backend_openssl3.c
> 	static void openssl_mac_backend(void)
> 	static void openssl_kmac_backend(void)
> 	static void openssl_dh_backend(void)
> 	static void openssl_ecdh_backend(void)
> 	static void openssl_drbg_backend(void)
> 	static void openssl_kdf_tls_backend(void)
> 	static void openssl_kdf_ssh_backend(void)
> 	static void openssl_kdf_108_backend(void)
> 	static void openssl_dsa_backend(void)
> 	static void openssl_ecdsa_backend(void)
> 
> Please also find the detailed debug log attached.
> [acvp-parser_openssl3-fails-to-process-RSA-Json-file.txt](https://github.com
> /smuellerDD/acvpparser/files/9153729/acvp-parser_openssl3-fails-to-process-R
> SA-Json-file.txt)


Ciao
Stephan

**Comment by jbmukund** [comment]
Hi Stephan,

any update on this one?

I don't see any support for RSA in openssl3? checked in in the below file
https://github.com/smuellerDD/acvpparser/blob/master/backends/backend_openssl3.c

Can you please provide an ETA when will this be ready. I can help add the support based on 
https://github.com/smuellerDD/acvpparser/blob/master/backends/backend_openssl.c if that's ok with you.

Also please provide your opinion on these issues:
======================================
DSA/ECDSA failures:
-----------------------------
/bin/acvp-parser_openssl sw/741192_ECDSA_keyGen/testvector-request.json /tmp/res.json
sw/741192_ECDSA_keyGen/testvector-request.json is located at: [https://drive.google.com/file/d/1lflXqb_zFeKdZ4gSfz2DMOGdWeIk-NnT/view?usp=sharing](url)

The below test fail
	741187_DSA_pqgGen
	741192_ECDSA_keyGen

	failure logs:
	ACVPParser (00:37:58) Verbose [parser/parser_dsa.c:register_dsa_impl:504]: Backend DSA registered               // GOOD thing: backend is registered
	Failed running /bin/acvp-parser_openssl against 741187_DSA_pqgGen/testvector-request.json: exit code 22                 partial

	reasons for ECDSA:
	ACVPParser (00:37:58) Verbose [parser/parser_ecdsa.c:register_ecdsa_impl:455]: Backend ECDSA registered         // GOOD thing: backend is registered


	My Reasoning:
	---------------------
	When looking at 741192_ECDSA_keyGen,
	 The reason these fail is because acp_parser failed to Process the very First tcId of the tgId:1
	 It could not find any pertinent data to match against the json_entry { "qx", "qy", "d", "curve", "tests" }. and it true if you look an entry in the json file.

	Please see the snippet of json file.
	     {
		"tgId": 1,
		"testType": "AFT",
		"tests": [
		  {
		    "tcId": 1
		    <<<<<<<<<<<<<<<<<<<<< Missing entry the lets the code decide which callback to call. parser/parser_ecdsa.c +457
		  },
		  {
		    "tcId": 2
		  },
		  {
		    "tcId": 3
		  }
		],
		"curve": "P-256",
		"secretGenerationMode": "extra bits"
	      },
  
Note that sw/741194_ECDSA_sigGen/testvector-request.json does not have the same issue. It works just fine.
 [https://drive.google.com/file/d/1SqcUmJgNbnEXY8t-fJ8Oh1OGyoi2DyNR/view?usp=sharing](url)

safePrimes & kdf 
-----------------------
Also, I am noticing failures for safePrimes & kdf as well. Is there support for then in acvp parser?

Thanks,
Mukund J

**Comment by smuellerDD** [comment]
code pushed
