### ISSUE TITLE
DSA/ECDSA failure

### ISSUE THREAD

**Issue by jbmukund** [smuellerDD/acvpparser#54]
Hi Stephan,

Thanks for adding support for RSA backend support for openssl3.

please provide your opinion on these issues as well:

DSA/ECDSA failures:
/bin/acvp-parser_openssl sw/741192_ECDSA_keyGen/testvector-request.json /tmp/res.json
sw/741192_ECDSA_keyGen/testvector-request.json is located at: [https://drive.google.com/file/d/1lflXqb_zFeKdZ4gSfz2DMOGdWeIk-NnT/view?usp=sharing](https://github.com/smuellerDD/acvpparser/issues/url)

The below test fail
741187_DSA_pqgGen
741192_ECDSA_keyGen

failure logs:
ACVPParser (00:37:58) Verbose [parser/parser_dsa.c:register_dsa_impl:504]: Backend DSA registered               // GOOD thing: backend is registered
Failed running /bin/acvp-parser_openssl against 741187_DSA_pqgGen/testvector-request.json: exit code 22                 partial

reasons for ECDSA:
ACVPParser (00:37:58) Verbose [parser/parser_ecdsa.c:register_ecdsa_impl:455]: Backend ECDSA registered         // GOOD thing: backend is registered

My suspicion: 
------------------
When looking at 741192_ECDSA_keyGen,
 The reason these fail is because acp_parser failed to Process the very First tcId of the tgId:1
 It could not find any pertinent data to match against the json_entry { "qx", "qy", "d", "curve", "tests" }. and it true if you look an entry in the json file.

Please see the snippet of json file.
     {
	"tgId": 1,
	"testType": "AFT",
	"tests": [
	  {
	    "tcId": 1
	    <<<<<<<<<<<<<<<<<<<<< Missing entry the lets the code decide which callback to call. parser/parser_ecdsa.c +457
	  },
	  {
	    "tcId": 2
	  },
	  {
	    "tcId": 3
	  }
	],
	"curve": "P-256",
	"secretGenerationMode": "extra bits"
      },
Note that sw/741194_ECDSA_sigGen/testvector-request.json does not have the same issue. It works just fine.
[https://drive.google.com/file/d/1SqcUmJgNbnEXY8t-fJ8Oh1OGyoi2DyNR/view?usp=sharing](https://github.com/smuellerDD/acvpparser/issues/url)

Can you please review and provide you insight?

Thanks,
Mukund J

**Comment by smuellerDD** [comment]
Support for OpenSSL3 has been updated. If the issue persists, please reopen issue.
