### ISSUE TITLE
Linking OpenSSL for Windows platform 

### ISSUE THREAD

**Issue by ashahhosse** [smuellerDD/acvpparser#55]
Hello -- we have been trying to get our ACVP parser to link to OpenSSL, but the linker complains it isn’t able to link to OpenSSL during the final step when it is being done by visual studio.  Do we need to do anything special for linking?  We are using OpenSSL 1.1.1 targeting a build for windows platform.  

Thank you!

**Comment by smuellerDD** [comment]
Am Mittwoch, 21. September 2022, 22:53:09 CEST schrieb ashahhosse:

Hi ashahhosse,

> Hello -- we have been trying to get our ACVP parser to link to OpenSSL, but
> the linker complains it isn’t able to link to OpenSSL during the final step
> when it is being done by visual studio.  Do we need to do anything special
> for linking?  We are using OpenSSL 1.1.1 targeting a build for windows
> platform.  

You need the fipsified OpenSSL version. The standard version of OpenSSL does 
not have FIPS code. And yes, OpenSSL-2.x will not work either. Only the code 
you find in Linux distros works.
 
> Thank you!
> 
> -- 
> Reply to this email directly or view it on GitHub:
> https://github.com/smuellerDD/acvpparser/issues/55
> You are receiving this because you are subscribed to this thread.
> 
> Message ID: ***@***.***>


Ciao
Stephan
