### ISSUE TITLE
Cross Compiling support

### ISSUE THREAD

**Issue by Jayukie** [smuellerDD/acvpparser#57]
Hi,
I want to cross compile acvpparser locally (and then execute it on the embedded arm platform). Is there a mature configuration scheme, or how should I modify it?
Thanks~

**Comment by smuellerDD** [comment]
Am Montag, 17. Oktober 2022, 05:09:44 CEST schrieb Jayukie:

Hi Jayukie,

> Hi,
> I want to cross compile acvpparser locally (and then execute it on the
> embedded arm platform). Is there a mature configuration scheme, or how
> should I modify it? Thanks~

The parser is written in clean C99 with only one dependency: POSIX API. Thus, 
the parser is executable pretty much anywhere. This is confirmed in a lot of 
places.

The only change you have to apply is the use of the proper backend.

Ciao
Stephan

**Comment by Jayukie** [comment]
OK, thank you. I have successfully cross compiled.
