### ISSUE TITLE
make openssl failed

### ISSUE THREAD

**Issue by laogaolao** [smuellerDD/acvpparser#64]
hi,

I tried to compile with command 'make openssl' but not sucessful.

gcc -Wextra -Wall -pedantic -fPIE -O2 -Wno-long-long -Werror -DACVP_PARSER_IUT=\"openssl\" -g -std=c11 -Wno-variadic-macros -DUBUNTU -D_FORTIFY_SOURCE=2 -fstack-protector-strong -fwrapv --param ssp-buffer-size=4 -Iparser   -c -o backends/backend_openssl_common.o backends/backend_openssl_common.c
backends/backend_openssl_common.c: In function ‘openssl_mct_update’:
backends/backend_openssl_common.c:756:45: error: invalid use of incomplete typedef ‘EVP_CIPHER_CTX’ {aka ‘struct evp_cipher_ctx_st’}
  756 |                         BN_bn2bin(tweak, ctx->iv + data->iv.len - BN_num_bytes(tweak));

Before compile this, I download the openssl 3.0 and installed and also set the LD_LIBRARY_PATH=/usr/lib64/

the platform is Ubuntu 22.04.2 LTS vm.

Thanks in advance.

**Comment by smuellerDD** [comment]
Am Freitag, 7. Juli 2023, 10:44:20 CEST schrieb laogaolao:

Hi laogaolao,

> hi,
> 
> I tried to compile with command 'make openssl' but not sucessful.
> 
> gcc -Wextra -Wall -pedantic -fPIE -O2 -Wno-long-long -Werror
> -DACVP_PARSER_IUT=\"openssl\" -g -std=c11 -Wno-variadic-macros -DUBUNTU
> -D_FORTIFY_SOURCE=2 -fstack-protector-strong -fwrapv --param
> ssp-buffer-size=4 -Iparser   -c -o backends/backend_openssl_common.o
> backends/backend_openssl_common.c backends/backend_openssl_common.c: In
> function ‘openssl_mct_update’: backends/backend_openssl_common.c:756:45:
> error: invalid use of incomplete typedef ‘EVP_CIPHER_CTX’ {aka ‘struct
> evp_cipher_ctx_st’} 756 |                         BN_bn2bin(tweak, ctx->iv
> + data->iv.len - BN_num_bytes(tweak));
> 
> Before compile this, I download the openssl 3.0 and installed and also set
> the LD_LIBRARY_PATH=/usr/lib64/
> 
> the platform is Ubuntu 22.04.2 LTS vm.
> 
> Thanks in advance.

git pull

Ciao
Stephan

**Comment by laogaolao** [comment]
It works now, thanks.
