### ISSUE TITLE
Unknown cipher algorithm KAS2

### ISSUE THREAD

**Issue by zkuperman** [smuellerDD/acvpparser#69]
I'm running a KAS-IFC-SSC vector. When the parser hits a test group that uses KAS2, it throws this error:

ACVPParser (13:51:07) Debug [parser/algorithms.c:convert_algo_cipher:218]: Convert cipher KAS2 into internal representation
ACVPParser (13:51:07) Warning [parser/parser_common.c:parse_one_entry:995]: Unknown cipher algorithm KAS2
ACVPParser (13:51:07) Debug [parser/parser_common.c:parse_all_processdata:1139]: Failure with return code -22

I noticed that in the conv struct above convert_algo_cipher(), KAS1 is listed along with KAS1-basic. KAS2-basic is listed, but 'KAS2' is missing. Can I add 'KAS2' using the same schema as KAS2-basic and still get a valid result?

**Comment by smuellerDD** [comment]
Am Donnerstag, 26. Oktober 2023, 20:01:40 CET schrieb Zalman Kuperman:

Hi Zalman,

> I'm running a KAS-IFC-SSC vector. When the parser hits a test group that
> uses KAS2, it throws this error:
> 
> ACVPParser (13:51:07) Debug [parser/algorithms.c:convert_algo_cipher:218]:
> Convert cipher KAS2 into internal representation ACVPParser (13:51:07)
> Warning [parser/parser_common.c:parse_one_entry:995]: Unknown cipher
> algorithm KAS2 ACVPParser (13:51:07) Debug
> [parser/parser_common.c:parse_all_processdata:1139]: Failure with return
> code -22
> 
> I noticed that in the conv struct above convert_algo_cipher(), KAS1 is
> listed along with KAS1-basic. KAS2-basic is listed, but 'KAS2' is missing.
> Can I add 'KAS2' using the same schema as KAS2-basic and still get a valid
> result?

Yes, that can be added.

Ciao
Stephan

**Comment by zkuperman** [comment]
Hi Stephan,
    I am running this on windows, using Ubuntu 22.04 WSL.
When I add KAS2 to the struct in parser/algorithms.c, the vector is able to run, but the KAS2 results are all wrong.
If KAS2 is not added to the conv struct, the vector fails with the error mentioned above.
I'm not sure how to troubleshoot this. Can you give me any advice?

**Comment by smuellerDD** [comment]
Am Donnerstag, 21. Dezember 2023, 22:48:08 CET schrieb Zalman Kuperman:

Hi Zalman,

> Hi Stephan,
>     I am running this on windows, using Ubuntu 22.04 WSL.
> When I add KAS2 to the struct in parser/algorithms.c, the vector is able to
> run, but the KAS2 results are all wrong. If KAS2 is not added to the conv
> struct, the vector fails with the error mentioned above. I'm not sure how
> to troubleshoot this. Can you give me any advice?

Sorry, but that email seems to have fallen through the cracks.

Check with the latest code drop. That code works for us along with the test 
vectors requested via the ACVP Proxy.

Ciao
Stephan
