### ISSUE TITLE
The kdf component mode in ansix9.63

### ISSUE THREAD

**Issue by angelshadow** [smuellerDD/acvpparser#7]
I found that the code don`t have the kdf component parser of mode ansix9.63? How to implement the parser of this  mode and the backend of it?

**Comment by smuellerDD** [comment]
Am Sonntag, dem 10.01.2021 um 20:29 -0800 schrieb angelshadow:
> I found that the code don`t have the kdf component parser of mode ansix9.63?
> How to implement the parser of this  mode and the backend of it?
> 

Yes, I have not implemented it yet as I do not have any IUT that supports it.

To implement a new parser for a cipher, please consider
https://github.com/smuellerDD/acvpparser/blob/master/README.hacking.md

Ciao
Stephan
