### ISSUE TITLE
Support for NSS

### ISSUE THREAD

**Issue by Declan-Y** [smuellerDD/acvpparser#70]
Hi, 
I noticed there is support for NSS in the makefile but some of the backend files needed are missing. How can I configure this for use with NSS? 

Thank you

**Comment by smuellerDD** [comment]
Am Dienstag, 21. November 2023, 12:04:34 CET schrieb Declan Young:

Hi Declan,

> Hi,
> I noticed there is support for NSS in the makefile but some of the backend
> files needed are missing. How can I configure this for use with NSS?

You cannot - that backend (just like all other backends defined in the 
Makefile but not present in backends/) are proprietary.

My lab shares it with vendors as part of an ongoing FIPS validation.
> 
> Thank you


Ciao
Stephan
