### ISSUE TITLE
Buffer alloc error with ECDH test vector

### ISSUE THREAD

**Issue by goatold** [smuellerDD/acvpparser#73]
Error
'''
ACVPParser (17:26:45) Warning [parser/stringhelper.c:alloc_buf:132]: Allocate an already allocated buffer!                                                                                                                           ACVPParser (17:26:45) Debug [backends/backend_openssl3.c:openssl_pkey_get_bn_bytes:71]: Failure with return code -14
'''

Env OS: 5.15.146.1-microsoft-standard-WSL2 #1 SMP Thu Jan 11 04:09:03 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
version: 
'''
ACVP Parser executing the crypto implementation openssl
ACVP Parser version: ACVPParser/2.1.6
'''
'''
openssl list -providers                                                                                                                                                                        Providers:
  default
    name: OpenSSL Default Provider
    version: 3.1.6
    status: active
  fips
    name: OpenSSL FIPS Provider
    version: 3.1.6
    status: active
'''
Input test vector
'''
[
   {
      "acvVersion": "1.0"
   },
   {
      "vsId": 2241895,
      "algorithm": "KAS-ECC",
      "mode": "CDH-Component",
      "revision": "Sp800-56Ar3",
      "isSample": true,
      "testGroups": [
         {
            "tgId": 1,
            "testType": "AFT",
            "curve": "P-224",
            "tests": [
               {
                  "tcId": 1,
                  "publicServerX": "005E622F7130019B3495622097A25E2CF2D53486A4683636ACD73594",
                  "publicServerY": "9E16A91A0EA5EC218155DC59215309A5BEED8C5A4D9246FA51E1C057"
               },
               {
                  "tcId": 2,
                  "publicServerX": "DE75212567E07079CCEB362558D70ADB9B32D779EEE9B6A7EAA2BC68",
                  "publicServerY": "9A421EA9DEC33970564CF2586597BE443ED04F318E3F5B1256B0A7AB"
               }
            ]
        }
     ]
  }
]
'''

**Comment by smuellerDD** [comment]
Am Freitag, 12. April 2024, 16:21:25 MESZ schrieb Leo Wang:

Hi Leo,

> Error
> '''
> ACVPParser (17:26:45) Warning [parser/stringhelper.c:alloc_buf:132]:
> Allocate an already allocated buffer!                                      
>                                                                            
>         ACVPParser (17:26:45) Debug
> [backends/backend_openssl3.c:openssl_pkey_get_bn_bytes:71]: Failure with
> return code -14 '''

Could you please provide some more logs following this one as this function is 
called in several places. Thanks.

Ciao
Stephan

**Comment by smuellerDD** [comment]
Fixed
