### ISSUE TITLE
EVP_PKEY_CTX_new_from_name failing when testing EDDSA 

### ISSUE THREAD

**Issue by rahulcode60** [smuellerDD/acvpparser#77]
Hi,

I am doing EDDSA singgen, sigver, keygen vector testing and I am using openssl version 3.2.0.

but this **EVP_PKEY_CTX_new_from_name**  api is failing.

**Comment by rahulcode60** [comment]
Hi @smuellerDD,

I am currently using opensource openssl v 3.2.0.

**Comment by smuellerDD** [comment]
Am Donnerstag, 2. Mai 2024, 16:55:47 MESZ schrieb rahulcode60:

Hi rahulcode60,

> Hi @smuellerDD,
> 
> I am currently using opensource openssl v 3.2.0.

Sure, but is the fips.so provider exporting the curve? At least I do not know.

If you like, you can add the logic to report the OpenSSL error:

CKINT_O_LOG(EVP_PKEY_keygen_init(ctx), "OpenSSL error: %s\n", 
ERR_error_string(ERR_get_error(), NULL));

Ciao
Stephan

**Comment by smuellerDD** [comment]
Please reopen if issue persists.
