### ISSUE TITLE
Cannot build for BoringSSL

### ISSUE THREAD

**Issue by upadhyaym** [smuellerDD/acvpparser#8]
Trying to build the parser for BoringSSL and it fails:

make: *** No rule to make target 'backends/backend_boringssl.c', needed by 'backends/backend_boringssl.o'.  Stop.

I checked the backends directory and there is no backend_boringssl.c. Building using 'make boringssl'. I modified the static library path in Makefile as suggested in README. Is there anything I am missing here?

**Comment by smuellerDD** [comment]
Am Montag, dem 11.01.2021 um 15:05 -0800 schrieb upadhyaym:
> Trying to build the parser for BoringSSL and it fails:
> 
> make: *** No rule to make target 'backends/backend_boringssl.c', needed by
> 'backends/backend_boringssl.o'.  Stop.
> 
> I checked the backends directory and there is no backend_boringssl.c.
> Building using 'make boringssl'. I modified the static library path in
> Makefile as suggested in README. Is there anything I am missing here?
> 

Well, you are missing the boringssl backend file. Currently, this backend is
not open source but can be made available as part of a validation atsec
information security.
