### ISSUE TITLE
LDT SHA tests are killed

### ISSUE THREAD

**Issue by vkosuri** [smuellerDD/acvpparser#83]
The ACVP Parser killed while running Long Duration Tests for SHA2-256, what is recommended size to run these test vectors?

```JSON
[
  {
    "acvVersion": "1.0"
  },
  {
    "vsId": 2409026,
    "algorithm": "SHA2-256",
    "revision": "1.0",
    "isSample": false,
    "testGroups": [
      {
        "tgId": 3,
        "testType": "LDT",
        "tests": [
          {
            "tcId": 514,
            "largeMsg": {
              "content": "72C0F63E1F7C371C",
              "contentLength": 64,
              "fullLength": 68719476736,
              "expansionTechnique": "repeating"
            }
          }
        ]
      }
    ]
  }
]
```

```sh
ACVPParser (13:48:04) Debug [parser/parser_common.c:match_entry:56]: Matching largeMsg (parsed_flags 32, entry flags 64424509472)
ACVPParser (13:48:04) Debug [parser/parser_common.c:parse_one_entry:1047]: Parsing object for JSON key largeMsg
ACVPParser (13:48:04) Debug [parser/read_json.c:json_find_key:58]: JSON field tgId does not exist
ACVPParser (13:48:04) Debug [parser/parser_common.c:match_entry:56]: Matching content (parsed_flags 32, entry flags 64424509472)
ACVPParser (13:48:04) Debug [parser/parser_common.c:parse_one_entry:954]: Get binary data for content
ACVPParser (13:48:04) Debug [parser/read_json.c:json_get_bin:183]: Found binary data for key content with value 72C0F63E1F7C371C
ACVPParser (13:48:04) Debug [parser/parser_common.c:match_entry:56]: Matching fullLength (parsed_flags 32, entry flags 64424509472)
ACVPParser (13:48:04) Debug [parser/read_json.c:json_get_uint64:146]: Found integer fullLength with value 68719476736
ACVPParser (13:48:04) Debug [parser/parser_common.c:match_entry:56]: Matching callback (parsed_flags 32, entry flags 64424509473)
Killed
```

**Comment by smuellerDD** [comment]
Perhaps the OOM killer killed the app considering it must allocate that amount of memory?Von meinem iPad gesendetAm 09.07.2024 um 19:23 schrieb Mallikarjunarao Kosuri ***@***.***>:﻿
The ACVP Parser killed while running Long Duration Tests for SHA2-256, what is recommended size to run these test vectors?
[
  {
    "acvVersion": "1.0"
  },
  {
    "vsId": 2409026,
    "algorithm": "SHA2-256",
    "revision": "1.0",
    "isSample": false,
    "testGroups": [
      {
        "tgId": 3,
        "testType": "LDT",
        "tests": [
          {
            "tcId": 514,
            "largeMsg": {
              "content": "72C0F63E1F7C371C",
              "contentLength": 64,
              "fullLength": 68719476736,
              "expansionTechnique": "repeating"
            }
          }
        ]
      }
    ]
  }
]
ACVPParser (13:48:04) Debug [parser/parser_common.c:match_entry:56]: Matching largeMsg (parsed_flags 32, entry flags 64424509472)
ACVPParser (13:48:04) Debug [parser/parser_common.c:parse_one_entry:1047]: Parsing object for JSON key largeMsg
ACVPParser (13:48:04) Debug [parser/read_json.c:json_find_key:58]: JSON field tgId does not exist
ACVPParser (13:48:04) Debug [parser/parser_common.c:match_entry:56]: Matching content (parsed_flags 32, entry flags 64424509472)
ACVPParser (13:48:04) Debug [parser/parser_common.c:parse_one_entry:954]: Get binary data for content
ACVPParser (13:48:04) Debug [parser/read_json.c:json_get_bin:183]: Found binary data for key content with value 72C0F63E1F7C371C
ACVPParser (13:48:04) Debug [parser/parser_common.c:match_entry:56]: Matching fullLength (parsed_flags 32, entry flags 64424509472)
ACVPParser (13:48:04) Debug [parser/read_json.c:json_get_uint64:146]: Found integer fullLength with value 68719476736
ACVPParser (13:48:04) Debug [parser/parser_common.c:match_entry:56]: Matching callback (parsed_flags 32, entry flags 64424509473)
Killed

**Comment by vkosuri** [comment]
I figured I had increased my Kubectl pod limits to 64GB, and now these are passing.
