### ISSUE TITLE
Support for XTS in backend_kcapi_lrng

### ISSUE THREAD

**Issue by rahulcode60** [smuellerDD/acvpparser#89]
I want to test XTS on backend_kcapi_lrng are there any plans to add XTS to it?

**Comment by smuellerDD** [comment]
Am Donnerstag, 3. Oktober 2024, 08:23:08 MESZ schrieb rahulcode60:

Hi rahulcode60,

> I want to test XTS on backend_kcapi_lrng are there any plans to add XTS to
> it?

This backend is intended to cover the algorithms of my LRNG patch series. 
Thus, it will not be extended by me in any way.

However, we have a closed-source version of this test code which covers all 
algrithms. This code is being made available to everybody conducting a FIPS 
140 validation with the lab I am working for: atsec. If you are interested, I 
can connect you with my colleagues.

Ciao
Stephan
