### ISSUE TITLE
acvp-parser 2.1.8 release timeline

### ISSUE THREAD

**Issue by shivania2** [smuellerDD/acvpparser#93]
I can see you have made a commit for acvp-parser-v2.1.8 release(https://github.com/smuellerDD/acvpparser/commit/bf5a5cbeedfd8e0320f91ae5e03fe31df2f94e04). But tar file has not yet been released.

Is there any anticipated timeline decided for the release of acvp-parser-v2.1.8 tar file?

**Comment by smuellerDD** [comment]
Am Mittwoch, 11. Dezember 2024, 09:35:39 Mitteleuropäische Normalzeit schrieb 
shivania2:

Hi shivania2,

> I can see you have made a commit for acvp-parser-v2.1.8
> release(https://github.com/smuellerDD/acvpparser/commit/bf5a5cbeedfd8e0320f
> 91ae5e03fe31df2f94e04). But tar file has not yet been released.
> 
> Is there any anticipated timeline decided for the release of
> acvp-parser-v2.1.8 tar file?

I currently have no timeline as of now, as the changes are random in nature to 
react on changes in either the ACVP protocol or the covered libraries. As 
releases are not really linked with anything, I am not sure based on which 
grounds I should plan a release or not.

Ciao
Stephan

**Comment by shivania2** [comment]
Thank You Stephen for the clarification.

Regards,
Shivani
